// Authentication actions
export const Auth = {
  SIGN_IN_REQUEST: 'SIGN_IN_REQUEST',
  SIGN_IN: 'SIGN_IN',
  SIGN_OUT: 'SIGN_OUT',
  SIGN_IN_REQUEST_ERRORS: 'SIGN_IN_REQUEST_ERRORS',
  SIGN_IN_STOP: 'SIGN_IN_STOP',
  SET_ERRORS: 'SET_SIGNUP_ERRORS',
  RESET_ERRORS: 'RESET_SIGNUP_ERRORS',
  SIGN_UP_REQUEST: 'SIGN_UP_REQUEST',
  STOP_SIGN_UP_REQUEST: 'STOP_SIGN_UP_REQUEST',
  CODE_REQUEST: 'AUTH_USER_CODE_REQUEST',
  CODE_SENT: 'AUTH_USER_CODE_SENT',
  CODE_REQUEST_STOP: 'AUTH_USER_CODE_REQUEST_STOP',
  GET_USER_DATA: 'GET_USER_DATA',
  SET_USER_DATA: 'SET_USER_DATA',
  STOP_USER_DATA: 'STOP_USER_DATA',
  SET_USER_PHONE: 'SET_USER_PHONE',
  GET_USER_PHONE: 'GET_USER_PHONE',
  SET_PHONE_CHECK: 'SET_PHONE_CHECK',
  GET_PHONE_CHECK: 'GET_PHONE_CHECK',
  GET_TOKEN: 'GET_TOKEN',
  SET_TOKEN: 'SET_TOKEN',
  UPDATE_USER_DATA: 'UPDATE_USER_DATA',
  UPDATED_USER_DATA: 'UPDATED_USER_DATA',
  UPDATE_CONSUME: 'UPDATE_CONSUME',
  UPDATE_CREDITS: 'UPDATE_CREDITS',
  UPDATE_PENDING_CREDITS: 'UPDATE_PENDING_CREDITS',
};

export const User = {
  UPDATE_USER_DATA: 'UPDATE_USER_DATA',
  UPDATED_USER_DATA: 'UPDATED_USER_DATA',
};

//Toast messages
export const FlashMessage = {
  INFO: 'FLASH_INFO_MESSAGE',
  ERROR: 'FLASH_ERROR_MESSAGE',
  WARNING: 'FLASH_WARNING_MESSAGE',
  CLOSE: 'FLASH_MESSAGE_CLOSE',
  SUCCESS: 'FLASH_MESSAGE_SUCCESS',
};

//async queue
export const AsyncQueue = {
  PUSH: 'PUSH_TO_QUEUE',
  POP: 'POP_FROM_QUEUE',
};

export const Customer = {
  SEARCH: 'SEARCH_CUSTOMER',
  SET_CUSTOMER_LIST: 'SET_CUSTOMER_LIST',
  SET_CUSTOMER: 'SET_CUSTOMER',
  RESET_SEARCH: 'RESET_CUSTOMER_SEARCH',
};

export const Recharge = {
  GET_ALL: 'GET_ALL',
  GET_ONE: 'GET_ONE',
  DO_RECHARGE: 'DO_RECHARGE',
  SET_AMOUNT: 'SET_AMOUNT',
  GET_AMOUNT: 'GET_AMOUNT',
  SET_RECHARGED: 'SET_RECHARGED',
  SET_DONE: 'SET_DONE',
};

export const Purchase = {
  RESET_PURCHASE: 'RESET_PURCHASE',
  GET_ALL: 'GET_ALL',
  GET_ONE: 'GET_ONE',
  SET_COMPANY: 'SET_COMPANY',
  SET_AMOUNT: 'SET_AMOUNT',
  SET_LOADING: 'PURCHASE_SET_LOADING',
  STOP_LOADING: 'PURCHASE_STOP_LOADING',
};

export const Company = {
  GET_ALL: 'GET_ALL',
  GET_ONE: 'GET_ONE',
  SET_COMPANY: 'SET_COMPANY',
  CLEAR: 'CLEAR',
  REQUEST_COMPANIES: 'REQUEST_COMPANIES',
  STOP_LOADING: 'COMPANY_STOP_LOADING',
};

export const Attendant = {
  GET_PURCHASE: 'ATTENDANT_GET_PURCHASE',
  REQUEST_GET_PURCHASE: 'ATTENDANT_REQUEST_GET',
  STOP_REQUEST_PURCHASE: 'ATTENDANT_STOP_REQUEST_PURCHASE',
  REQUEST_CONFIRM_PURCHASE: 'ATTENDANT_REQUEST_CONFIRM_PURCHASE',
  CONFIRM_PURCHASE: 'ATTENDANT_CONFIRM_PURCHASE',
  STOP_CONFIRM_PURCHASE: 'ATTENDANT_STOP_CONFIRM_PURCHASE',
  ERROR_CONFIRM_PURCHASE: 'ATTENDANT_ERROR_CONFIRM_PURCHASE',
};
